CREATE TABLE IF NOT EXISTS users
(
    id    INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(250)                         NOT NULL,
    email VARCHAR(254)                         NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat NUMERIC(9, 6)                        NOT NULL,
    lon NUMERIC(9, 6)                        NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                          NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         VARCHAR(2000)                        NOT NULL,
    category_id        INT                                  NOT NULL,
    created_on         TIMESTAMP                            NOT NULL,
    description        VARCHAR(7000)                        NOT NULL,
    initiator_id       INT                                  NOT NULL,
    event_date         TIMESTAMP                            NOT NULL,
    location_id        INT                                  NOT NULL,
    paid               BOOLEAN                              NOT NULL,
    participant_limit  INT                                  NOT NULL,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN                              NOT NULL,
    state              VARCHAR(20)                          NOT NULL,
    title              VARCHAR(120)                         NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_user FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_location FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE
);

CREATE INDEX idx_events_category ON events (category_id);

CREATE INDEX idx_events_user ON events (initiator_id);

CREATE INDEX idx_events_location ON events (location_id);

CREATE TABLE IF NOT EXISTS compilations
(
    id     INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN                              NOT NULL,
    title  VARCHAR(50)                          NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id),
    CONSTRAINT uq_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    id             INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compilation_id INT                                  NOT NULL,
    event_id       INT                                  NOT NULL,
    CONSTRAINT pk_compilation_events PRIMARY KEY (id),
    CONSTRAINT fk_compilation_event_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE,
    CONSTRAINT fk_compilation_event_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT uq_compilation_event UNIQUE (compilation_id, event_id)
);

CREATE INDEX idx_compilation_events_event ON compilation_events (event_id);

CREATE TABLE IF NOT EXISTS participants
(
    id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created      TIMESTAMP                            NOT NULL,
    event_id     INT                                  NOT NULL,
    requestor_id INT                                  NOT NULL,
    status       VARCHAR(20)                          NOT NULL,
    CONSTRAINT pk_participants PRIMARY KEY (id),
    CONSTRAINT fk_participants_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_participants_user FOREIGN KEY (requestor_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_event_user UNIQUE (event_id, requestor_id)
);

CREATE INDEX idx_participants_user ON participants (requestor_id);

CREATE INDEX idx_participants_event_status ON participants (event_id, status);

CREATE TABLE IF NOT EXISTS comments
(
    id             INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    commentator_id INT                                  NOT NULL,
    event_id       INT                                  NOT NULL,
    condition      VARCHAR(20)                          NOT NULL,
    comment        VARCHAR(1000)                        NOT NULL,
    commentDate    TIMESTAMP                            NOT NULL,
    edited_on      TIMESTAMP,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comment_user FOREIGN KEY (commentator_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT uq_user_event UNIQUE (commentator_id, event_id)
);

CREATE INDEX idx_comments_user ON comments (commentator_id);

CREATE INDEX idx_comments_event ON comments (event_id);