CREATE TABLE IF NOT EXISTS hits
(
    id         INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_name   VARCHAR(255)                         NOT NULL,
    uri        VARCHAR(255)                         NOT NULL,
    ip         VARCHAR(255)                         NOT NULL,
    time_stamp TIMESTAMP                            NOT NULL
);